version: "3"
services:
  project:
    build: .
    container_name: project-progress
    restart: always
    ports:
      - "4435:3000"
    volumes:
      - project_data:/app/data
volumes:
  project_data:
