version: "3"
services:
  project:
    build: .
    image: projectprocess:latest
    container_name: project-progress
    ports:
      - "4435:3000"
    volumes:
      - project_data:/app/backend/data
    restart: always

volumes:
  project_data:
